version: "3"
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    build: ./mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - ./mysql/local.env
    tty: true

  app:
    depends_on:
      - mysql
    container_name: fast_api
    build: ./app
    restart: unless-stopped
    tty: true
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - ./app/local.env
    networks:
      - test_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
      PMA_PORT: 3306
    ports:
      - "8090:80"
    depends_on:
      - mysql
    networks:
      - test_network

  # phpmyadmin:
  #   image: phpmyadmin:5.1.1
  #   environment:
  #     PMA_HOST: database
  #     PMA_USER: root
  #     PMA_PASSWORD:
  #     PMA_PORT: 3306
  #   ports:
  #     - "8090:80"
  #   depends_on:
  #     - database
  #   networks:
  #     - test_network
  #   restart: always

networks:
  test_network:
    driver: bridge

volumes:
  db-data:
    driver: local
