version: "3"
services:
  database:
    image: mysql:5.6
    container_name: fastapi-mysql-standalone
    environment:
       - MYSQL_ROOT_PASSWORD=
       - MYSQL_DATABASE=smart_conference_app
       - MYSQL_USER=root
       - MYSQL_ALLOW_EMPTY_PASSWORD=true
    build:
      context: ./mysql
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - db-data:/var/lib/mysql
    networks: 
      - test_network
    tty: true
    restart: always


  app:
    depends_on:
      - database
    container_name: fast_api
    build: ./app
    restart: unless-stopped
    tty: true
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - ./app/local.env
    networks: 
      - test_network



  # phpmyadmin:
  #   image: phpmyadmin:5.1.1
  #   environment:
  #     PMA_HOST: database
  #     PMA_USER: root
  #     PMA_PASSWORD:
  #     PMA_PORT: 3306
  #   ports:
  #     - "8090:80"
  #   depends_on:
  #     - database
  #   networks: 
  #     - test_network
  #   restart: always

networks: 
  test_network:
    driver: bridge

volumes:
  db-data:
    driver: local